services:
  front:
    build: ./frontend/carrito
    container_name: frontend
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "80:80"
  
  backend:
    build: ./backend
    container_name: backend
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      JWT_SECRET_KEY: test
      POSTGRES_DB: postgres
      FLASK_APP: ./src/main.py
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health-check || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5